from __future__ import annotations


STRINGS = {
    "zh_TW": {
        "window_title": "YGOPRO Blogger Tool",
        "source_status": "資料來源狀態",
        "selected": "已選擇",
        "not_selected": "未選擇",
        "optional": "可選",
        "html_tools": "HTML 格式整理",
        "paste_html": "貼上 HTML 草稿",
        "copy_export_html": "複製匯出 HTML",
        "size_placeholder": "大小",
        "size_title": "標題",
        "size_subtitle": "小標題",
        "size_normal": "一般",
        "clear_format": "清除格式",
        "search_title": "卡片搜尋",
        "search_keyword": "關鍵字",
        "search_placeholder": "輸入卡名或卡號",
        "copy_card": "複製圖片與文字",
        "cdb_editor": "CDB 編輯",
        "cdb_helper": "右側可直接編輯 cards.cdb。下拉欄位以文字為主，也能手動輸入數值。",
        "effect_placeholder": "效果文",
        "setcode_helper": "系列",
        "setcode_helper_placeholder": "可輸入十進位、0x十六進位，或 0x1234,0x5678",
        "setcode_helper_hint": "目前：{text}",
        "setcode_helper_empty": "尚未設定",
        "setcode_search_title": "setcode 搜尋",
        "setcode_search_keyword": "搜尋名稱",
        "setcode_search_language": "搜尋語言",
        "setcode_search_all": "中英皆可",
        "setcode_search_results": "搜尋結果",
        "setcode_search_button": "搜尋",
        "setcode_search_apply": "新增系列",
        "edit_extra_texts": "編輯 texts 擴充",
        "script_path": "腳本路徑",
        "script_placeholder": "-- 若存在，會連動讀取 script/c<卡號>.lua",
        "reload_script": "重新讀取",
        "save_script": "儲存腳本",
        "open_script_workshop": "開啟 Lua 工作台",
        "load_single_template": "套用 single.lua 範本",
        "load_current": "載入目前卡片",
        "save_changes": "儲存修改",
        "discard_changes": "放棄修改",
        "add_card": "新增卡片",
        "delete_card": "刪除卡片",
        "copy_from_secondary": "第二資料庫搜尋/比對",
        "extra_texts": "texts 擴充（str1 ~ str16）",
        "menu_file": "檔案",
        "menu_edit": "編輯",
        "menu_sources": "資料來源",
        "menu_language": "語言",
        "menu_pick_cdb": "選擇 cards.cdb",
        "menu_pick_secondary_cdb": "選擇第二個 cards.cdb",
        "menu_pick_pics": "選擇 pics 資料夾",
        "menu_reload_sources": "重新載入資料來源",
        "menu_copy_card": "複製圖片與文字",
        "menu_save_card": "儲存目前卡片",
        "language_zh_TW": "繁體中文",
        "language_en": "English",
        "field_id": "id",
        "field_name": "卡名",
        "field_ot": "ot",
        "field_type": "type",
        "field_alias": "alias",
        "field_setcode": "setcode",
        "field_atk": "atk",
        "field_def": "def",
        "field_level": "level",
        "field_race": "race",
        "field_attribute": "attribute",
        "field_category": "category",
        "field_desc": "效果文",
        "field_setcode_text": "系列",
        "field_current_card": "目前卡片",
        "field_secondary_card": "第二資料庫卡片",
        "no_data": "沒有資料請選擇資料來源。",
        "pick_cdb_title": "選擇 cards.cdb",
        "pick_secondary_cdb_title": "選擇第二個 cards.cdb",
        "pick_pics_title": "選擇 pics 資料夾",
        "warn_no_card_title": "未選擇卡片",
        "warn_no_card_text": "請先從左側列表選擇一張卡片。",
        "warn_no_repo_title": "沒有可用卡片",
        "warn_no_repo_text": "請先載入 cards.cdb 並選擇卡片。",
        "warn_no_secondary_title": "未選擇第二資料庫",
        "warn_no_secondary_text": "請先選擇第二個 cards.cdb。",
        "warn_secondary_not_found_title": "第二資料庫找不到卡片",
        "warn_secondary_not_found_text": "第二資料庫中找不到這張卡片。",
        "compare_window_title": "第二資料庫卡片搜尋 / 比對",
        "compare_search": "搜尋",
        "compare_search_placeholder": "輸入卡名或卡號",
        "compare_load_to_editor": "載入到編輯器",
        "copied_word": "已複製可貼到 Word 的圖片與文字。",
        "copied_html": "已複製匯出 HTML。",
        "loaded_html": "已將 HTML 草稿載入編輯器。",
        "loaded_sources": "已重新載入資料來源。",
        "missing_cdb": "尚未選擇 cards.cdb。",
        "loaded_editor": "已將目前卡片載入 CDB 編輯器。",
        "loaded_from_secondary": "已將第二資料庫中的卡片內容載入編輯器。",
        "reset_editor": "已重設成目前卡片內容。",
        "saved_card": "已儲存卡片修改並建立備份：{name}",
        "added_card": "已新增卡片並建立備份：{name}",
        "deleted_card": "已刪除卡片並建立備份：{name}",
        "script_loaded": "已讀取腳本：{name}",
        "script_saved": "已儲存腳本：{name}",
        "script_missing": "找不到腳本，已準備建立新檔。",
        "save_failed": "儲存失敗",
        "load_failed": "載入失敗",
        "confirm_delete_title": "確認刪除",
        "confirm_delete_text": "確定要刪除這張卡片嗎？\n{id} {name}",
        "field_required": "{name} 不能留空。",
        "name_required": "卡名不能留空。",
        "paste_dialog_title": "貼上 HTML 草稿",
        "paste_dialog_label": "貼上 Blogger HTML 草稿以便整理",
        "paste_dialog_placeholder": "在這裡貼上 Blogger HTML 原始碼",
        "cancel": "取消",
        "close": "關閉",
        "apply": "套用",
    },
    "en": {
        "window_title": "YGOPRO Blogger Tool",
        "source_status": "Source Status",
        "selected": "Selected",
        "not_selected": "Not Selected",
        "optional": "Optional",
        "html_tools": "HTML Format Tools",
        "paste_html": "Paste HTML Draft",
        "copy_export_html": "Copy Export HTML",
        "size_placeholder": "Size",
        "size_title": "Title",
        "size_subtitle": "Subtitle",
        "size_normal": "Normal",
        "clear_format": "Clear Format",
        "search_title": "Card Search",
        "search_keyword": "Keyword",
        "search_placeholder": "Enter card name or id",
        "copy_card": "Copy Image and Text",
        "cdb_editor": "CDB Editor",
        "cdb_helper": "Edit cards.cdb directly on the right. Option fields are text-first and still accept manual numeric input.",
        "effect_placeholder": "Effect text",
        "setcode_helper": "Series",
        "setcode_helper_placeholder": "Decimal, 0x hex, or 0x1234,0x5678",
        "setcode_helper_hint": "Current: {text}",
        "setcode_helper_empty": "Not set",
        "setcode_search_title": "setcode Search",
        "setcode_search_keyword": "Search Name",
        "setcode_search_language": "Search Language",
        "setcode_search_all": "Both",
        "setcode_search_results": "Results",
        "setcode_search_button": "Search",
        "setcode_search_apply": "Add Series",
        "edit_extra_texts": "Edit texts extras",
        "script_path": "Script Path",
        "script_placeholder": "-- Auto-linked to script/c<card_id>.lua when available",
        "reload_script": "Reload",
        "save_script": "Save Script",
        "open_script_workshop": "Open Lua Workshop",
        "load_single_template": "Use single.lua Template",
        "load_current": "Load Current Card",
        "save_changes": "Save Changes",
        "discard_changes": "Discard Changes",
        "add_card": "Add Card",
        "delete_card": "Delete Card",
        "copy_from_secondary": "Secondary Search / Compare",
        "extra_texts": "texts extras (str1 ~ str16)",
        "menu_file": "File",
        "menu_edit": "Edit",
        "menu_sources": "Sources",
        "menu_language": "Language",
        "menu_pick_cdb": "Select cards.cdb",
        "menu_pick_secondary_cdb": "Select Secondary cards.cdb",
        "menu_pick_pics": "Select pics Folder",
        "menu_reload_sources": "Reload Sources",
        "menu_copy_card": "Copy Image and Text",
        "menu_save_card": "Save Current Card",
        "language_zh_TW": "Traditional Chinese",
        "language_en": "English",
        "field_id": "id",
        "field_name": "Name",
        "field_ot": "ot",
        "field_type": "type",
        "field_alias": "alias",
        "field_setcode": "setcode",
        "field_atk": "atk",
        "field_def": "def",
        "field_level": "level",
        "field_race": "race",
        "field_attribute": "attribute",
        "field_category": "category",
        "field_desc": "Description",
        "field_setcode_text": "Series",
        "field_current_card": "Current Card",
        "field_secondary_card": "Secondary DB Card",
        "no_data": "No data. Please choose a data source.",
        "pick_cdb_title": "Select cards.cdb",
        "pick_secondary_cdb_title": "Select Secondary cards.cdb",
        "pick_pics_title": "Select pics Folder",
        "warn_no_card_title": "No Card Selected",
        "warn_no_card_text": "Please select a card from the list first.",
        "warn_no_repo_title": "No Card Available",
        "warn_no_repo_text": "Please load cards.cdb and select a card first.",
        "warn_no_secondary_title": "No Secondary Database",
        "warn_no_secondary_text": "Please select a secondary cards.cdb first.",
        "warn_secondary_not_found_title": "Card Not Found in Secondary DB",
        "warn_secondary_not_found_text": "The current card was not found in the secondary database.",
        "compare_window_title": "Secondary Database Search / Compare",
        "compare_search": "Search",
        "compare_search_placeholder": "Enter card name or id",
        "compare_load_to_editor": "Load Into Editor",
        "copied_word": "Copied card image and text for Word.",
        "copied_html": "Copied exported HTML.",
        "loaded_html": "Loaded HTML draft into the editor.",
        "loaded_sources": "Reloaded data sources.",
        "missing_cdb": "cards.cdb has not been selected.",
        "loaded_editor": "Loaded current card into the CDB editor.",
        "loaded_from_secondary": "Loaded card data from the secondary database into the editor.",
        "reset_editor": "Reset the editor to the current card values.",
        "saved_card": "Saved card changes and created backup: {name}",
        "added_card": "Added card and created backup: {name}",
        "deleted_card": "Deleted card and created backup: {name}",
        "script_loaded": "Loaded script: {name}",
        "script_saved": "Saved script: {name}",
        "script_missing": "Script file was not found. A new file will be created on save.",
        "save_failed": "Save Failed",
        "load_failed": "Load Failed",
        "confirm_delete_title": "Confirm Delete",
        "confirm_delete_text": "Delete this card?\n{id} {name}",
        "field_required": "{name} cannot be empty.",
        "name_required": "Card name cannot be empty.",
        "paste_dialog_title": "Paste HTML Draft",
        "paste_dialog_label": "Paste the Blogger HTML draft to normalize",
        "paste_dialog_placeholder": "Paste Blogger HTML source here",
        "cancel": "Cancel",
        "close": "Close",
        "apply": "Apply",
    },
}


OPTION_LABELS = {
    "ot": {
        1: {"zh_TW": "OCG / TCG", "en": "OCG / TCG"},
        2: {"zh_TW": "動畫", "en": "Anime"},
        4: {"zh_TW": "非法", "en": "Illegal"},
        8: {"zh_TW": "遊戲", "en": "Video Game"},
        16: {"zh_TW": "自訂", "en": "Custom"},
    },
    "attribute": {
        0: {"zh_TW": "無", "en": "None"},
        1: {"zh_TW": "地屬性", "en": "Earth"},
        2: {"zh_TW": "水屬性", "en": "Water"},
        4: {"zh_TW": "炎屬性", "en": "Fire"},
        8: {"zh_TW": "風屬性", "en": "Wind"},
        16: {"zh_TW": "光屬性", "en": "Light"},
        32: {"zh_TW": "闇屬性", "en": "Dark"},
        64: {"zh_TW": "神屬性", "en": "Divine"},
    },
    "race": {
        1: {"zh_TW": "戰士族", "en": "Warrior"},
        2: {"zh_TW": "魔法使族", "en": "Spellcaster"},
        4: {"zh_TW": "天使族", "en": "Fairy"},
        8: {"zh_TW": "惡魔族", "en": "Fiend"},
        16: {"zh_TW": "不死族", "en": "Zombie"},
        32: {"zh_TW": "機械族", "en": "Machine"},
        64: {"zh_TW": "水族", "en": "Aqua"},
        128: {"zh_TW": "炎族", "en": "Pyro"},
        256: {"zh_TW": "岩石族", "en": "Rock"},
        512: {"zh_TW": "鳥獸族", "en": "Winged Beast"},
        1024: {"zh_TW": "植物族", "en": "Plant"},
        2048: {"zh_TW": "昆蟲族", "en": "Insect"},
        4096: {"zh_TW": "雷族", "en": "Thunder"},
        8192: {"zh_TW": "龍族", "en": "Dragon"},
        16384: {"zh_TW": "獸族", "en": "Beast"},
        32768: {"zh_TW": "獸戰士族", "en": "Beast-Warrior"},
        65536: {"zh_TW": "恐龍族", "en": "Dinosaur"},
        131072: {"zh_TW": "魚族", "en": "Fish"},
        262144: {"zh_TW": "海龍族", "en": "Sea Serpent"},
        524288: {"zh_TW": "爬蟲類族", "en": "Reptile"},
        1048576: {"zh_TW": "念動力族", "en": "Psychic"},
        2097152: {"zh_TW": "幻神獸族", "en": "Divine Beast"},
        4194304: {"zh_TW": "創造神族", "en": "Creator God"},
        8388608: {"zh_TW": "幻龍族", "en": "Wyrm"},
        16777216: {"zh_TW": "電子界族", "en": "Cyberse"},
        33554432: {"zh_TW": "幻想魔族", "en": "Illusion"},
    },
    "type": {
        1: {"zh_TW": "怪獸", "en": "Monster"},
        17: {"zh_TW": "通常怪獸", "en": "Normal Monster"},
        33: {"zh_TW": "效果怪獸", "en": "Effect Monster"},
        545: {"zh_TW": "靈魂效果怪獸", "en": "Spirit Effect Monster"},
        1057: {"zh_TW": "同盟效果怪獸", "en": "Union Effect Monster"},
        2049: {"zh_TW": "二重怪獸", "en": "Gemini Monster"},
        2081: {"zh_TW": "二重效果怪獸", "en": "Gemini Effect Monster"},
        4097: {"zh_TW": "協調怪獸", "en": "Tuner Monster"},
        4113: {"zh_TW": "協調通常怪獸", "en": "Tuner Normal Monster"},
        4129: {"zh_TW": "協調效果怪獸", "en": "Tuner Effect Monster"},
        65: {"zh_TW": "融合怪獸", "en": "Fusion Monster"},
        81: {"zh_TW": "融合通常怪獸", "en": "Fusion Normal Monster"},
        97: {"zh_TW": "融合效果怪獸", "en": "Fusion Effect Monster"},
        129: {"zh_TW": "儀式怪獸", "en": "Ritual Monster"},
        145: {"zh_TW": "儀式通常怪獸", "en": "Ritual Normal Monster"},
        161: {"zh_TW": "儀式效果怪獸", "en": "Ritual Effect Monster"},
        257: {"zh_TW": "陷阱怪獸", "en": "Trap Monster"},
        513: {"zh_TW": "靈魂怪獸", "en": "Spirit Monster"},
        1025: {"zh_TW": "同盟怪獸", "en": "Union Monster"},
        8193: {"zh_TW": "同步怪獸", "en": "Synchro Monster"},
        8209: {"zh_TW": "同步通常怪獸", "en": "Synchro Normal Monster"},
        8225: {"zh_TW": "同步效果怪獸", "en": "Synchro Effect Monster"},
        16385: {"zh_TW": "衍生物", "en": "Token"},
        2097185: {"zh_TW": "反轉效果怪獸", "en": "Flip Effect Monster"},
        4194337: {"zh_TW": "卡通效果怪獸", "en": "Toon Effect Monster"},
        8388609: {"zh_TW": "超量怪獸", "en": "Xyz Monster"},
        8388625: {"zh_TW": "超量通常怪獸", "en": "Xyz Normal Monster"},
        8388641: {"zh_TW": "超量效果怪獸", "en": "Xyz Effect Monster"},
        16777233: {"zh_TW": "靈擺通常怪獸", "en": "Pendulum Normal Monster"},
        16777249: {"zh_TW": "靈擺效果怪獸", "en": "Pendulum Effect Monster"},
        16785441: {"zh_TW": "同步靈擺效果怪獸", "en": "Synchro Pendulum Effect Monster"},
        25165857: {"zh_TW": "超量靈擺效果怪獸", "en": "Xyz Pendulum Effect Monster"},
        67108865: {"zh_TW": "連結怪獸", "en": "Link Monster"},
        67108897: {"zh_TW": "連結效果怪獸", "en": "Link Effect Monster"},
        2: {"zh_TW": "魔法", "en": "Spell"},
        65538: {"zh_TW": "通常魔法", "en": "Normal Spell"},
        131074: {"zh_TW": "速攻魔法", "en": "Quick-Play Spell"},
        262146: {"zh_TW": "永續魔法", "en": "Continuous Spell"},
        524290: {"zh_TW": "裝備魔法", "en": "Equip Spell"},
        1048578: {"zh_TW": "場地魔法", "en": "Field Spell"},
        2097154: {"zh_TW": "儀式魔法", "en": "Ritual Spell"},
        4: {"zh_TW": "陷阱", "en": "Trap"},
        131076: {"zh_TW": "通常陷阱", "en": "Normal Trap"},
        262148: {"zh_TW": "永續陷阱", "en": "Continuous Trap"},
        524292: {"zh_TW": "反擊陷阱", "en": "Counter Trap"},
    },
    "category": {
        0: {"zh_TW": "無", "en": "None"},
        1: {"zh_TW": "破壞怪獸", "en": "Destroy Monster"},
        2: {"zh_TW": "破壞魔陷", "en": "Destroy Spell/Trap"},
        4: {"zh_TW": "返回", "en": "Bounce"},
        8: {"zh_TW": "檢索", "en": "Search"},
        16: {"zh_TW": "抽牌", "en": "Draw"},
        32: {"zh_TW": "特殊召喚", "en": "Special Summon"},
        64: {"zh_TW": "表示形式變更", "en": "Change Position"},
        128: {"zh_TW": "控制權變更", "en": "Control"},
        256: {"zh_TW": "墓地回收", "en": "Recycle Grave"},
        512: {"zh_TW": "除外", "en": "Banish"},
        1024: {"zh_TW": "回手牌", "en": "To Hand"},
        2048: {"zh_TW": "回牌組", "en": "To Deck"},
        4096: {"zh_TW": "送墓", "en": "Send to Grave"},
        8192: {"zh_TW": "破壞自身", "en": "Self Destroy"},
        16384: {"zh_TW": "無效", "en": "Negate"},
        32768: {"zh_TW": "變更等級", "en": "Change Level"},
        65536: {"zh_TW": "變更屬性", "en": "Change Attribute"},
        131072: {"zh_TW": "變更種族", "en": "Change Race"},
    },
}
